#!/usr/bin/env python3
"""R.java জেনারেটর।

aapt2 link-ও R.java বানায়, কিন্তু আমরা javac আগে চালাই — তাই রিসোর্স ফাইলের
নাম থেকে নিজেদের R ক্লাস বানিয়ে নেওয়া হয়। id-গুলো যেকোনো অ-শূন্য ধ্রুবক হলেই
চলে: aapt2 link-এর পরে আসল R.jar দিয়ে আবার কম্পাইল করে চূড়ান্ত class ফাইল বানানো
হয় (tools/build_apk.sh দেখুন)।
"""
import os
import re
import sys

RES = sys.argv[1] if len(sys.argv) > 1 else 'android/app/src/main/res'
OUT = sys.argv[2] if len(sys.argv) > 2 else 'build/gen/com/prakriti/kosh/R.java'
PKG = 'com.prakriti.kosh'

TYPES = ['attr', 'drawable', 'mipmap', 'color', 'string', 'dimen', 'style', 'xml',
         'layout', 'anim', 'raw', 'integer', 'array', 'id']

entries = {t: [] for t in TYPES}

# values/*.xml
for f in sorted(os.listdir(os.path.join(RES, 'values'))):
    if not f.endswith('.xml'):
        continue
    src = open(os.path.join(RES, 'values', f), encoding='utf-8').read()
    for tag, name in re.findall(
            r'<(color|string|dimen|style|integer|string-array|integer-array)\s+name="([^"]+)"',
            src):
        t = {'string-array': 'array', 'integer-array': 'array'}.get(tag, tag)
        if t not in entries:
            entries[t] = []
        entries[t].append(name)

# ফাইল-ভিত্তিক রিসোর্স
for d in sorted(os.listdir(RES)):
    m = re.match(r'(drawable|mipmap|layout|anim|raw|xml|color)(-.*)?$', d)
    if not m:
        continue
    t = m.group(1)
    for f in sorted(os.listdir(os.path.join(RES, d))):
        if not f.endswith('.xml') and not f.endswith('.png') and not f.endswith('.webp'):
            continue
        entries.setdefault(t, []).append(os.path.splitext(f)[0])


def const_name(name):
    return re.sub(r'[^A-Za-z0-9_]', '_', name)


lines = ['/* AUTO-GENERATED by tools/gen_r.py — হাতে সম্পাদনা করবেন না */',
         'package %s;' % PKG, '', 'public final class R {']
n = 0x7f010000
for t in TYPES:
    names = []
    seen = set()
    for raw in entries.get(t, []):
        c = const_name(raw)
        if c in seen:
            continue
        seen.add(c)
        names.append(c)
    if not names:
        continue
    lines.append('    public static final class %s {' % t)
    for c in sorted(names):
        n += 1
        lines.append('        public static final int %s = 0x%08x;' % (c, n))
    lines.append('    }')
lines.append('}')

os.makedirs(os.path.dirname(OUT), exist_ok=True)
open(OUT, 'w', encoding='utf-8').write('\n'.join(lines) + '\n')
print('wrote %s (%d types)' % (OUT, sum(1 for t in TYPES if entries.get(t))))
